### ISSUE TITLE
Error while setting up platform Toon in 0.90.1

### ISSUE THREAD

**Issue by Jeltel** [cyberjunky/home-assistant-custom-components#24]
After installing HA 0.90.1 the Toon climate component isn't working any more. I get the error below:

```
2019-03-24 18:55:14 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform toon
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 124, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 89, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'homeassistant.components.toon.climate' has no attribute 'setup_platform'
```

**Comment by Jeltel** [comment]
Nevermind, i see it's already fixed in the repo...
