### ISSUE TITLE
Plugwise 0.92.1

### ISSUE THREAD

**Issue by junrt** [cyberjunky/home-assistant-custom-components#29]
i am getting errors.
Help!

2019-04-29 20:16:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plugwise_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-29 20:16:23 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform plugwise_custom
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/plugwise_custom/switch.py", line 38, in setup_platform
    import plugwise
ModuleNotFoundError: No module named 'plugwise'

**Comment by cyberjunky** [comment]
I see you named the directory plugwise_custom, and perhaps didn't change the config entry to use same name?

But default directory plugwise should also work I guess (since there is no buildin plugwise module)

  **- platform: plugwise_custom**

**Comment by cyberjunky** [comment]
No response
