### ISSUE TITLE
ModuleNotFoundError: No module named 'homeassistant.components.plugwise.switch'

### ISSUE THREAD

**Issue by doets001** [cyberjunky/home-assistant-custom-components#46]
I can't get it working. The module seems to load, but I can't configure HA to see my circles.
 **1) de module seems to load**
2020-02-09 18:07:10 INFO (SyncWorker_12) [homeassistant.loader] Loaded plugwise from homeassistant.components.plugwise

**2) I did put the file on the location you metioned on git**
config # find custom-components/
custom-components/
custom-components/plugwise
custom-components/plugwise/switch.py
custom-components/plugwise/__init__.py
custom-components/plugwise/manifest.json

**3) The configuration in the configuration.yaml**
...
...
switch:
  - platform: rfxtrx
    automatic_add: true
    devices:
      0b11000c0032b3260b010f40:
        name: lamp_slaapkamer_MenS

  - platform: plugwise
    port: /dev/ttyUSB1
    circles:
      CirclePlus: 000D6F0000B81678
      Waterbed: 000D6F00044658F3
      Droger: 000D6F00044658D7
      Boiler: 000D6F00044658D7
      CentraleAfzuiging: 000D6F0003562AAC
...
...

4) the error in the logging
...
...
2020-02-09 18:13:27 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds.
2020-02-09 18:13:27 ERROR (MainThread) [homeassistant.config] Platform error: switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 760, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 265, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'homeassistant.components.plugwise.switch'
2020-02-09 18:13:27 INFO (MainThread) [homeassistant.setup] Setting up switch
...
...

And some general info:
- I'm running HA in a docker container: (homeassistant/home-assistant:stable)
Home Assistant 0.104.3
Path to configuration.yaml: /config
Frontend version: 20200108.2 - latest

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.6
timezone | UTC
version | 0.104.3
virtualenv | false

What I'm doing wrong?
Can you please help me?
The switch configured for the rfxtrx is working fine.

**Comment by cyberjunky** [comment]
Hi,

the directory custom-components should be called custom_components

**Comment by doets001** [comment]
Thnx! Stupid mistake :-).
It works now!
