### ISSUE TITLE
Home Assistant 0.63 update gives error message for toon_boilerstatus

### ISSUE THREAD

**Issue by RaJeronimo** [cyberjunky/home-assistant-custom-components#6]
Hi,

I'm not much of a python coder but want to share this error message when i update my home assistant HASSIO to 0.63. I hope someone can help?

`2018-02-12 20:44:04 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.toon_room_temp_setpoint fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 201, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 324, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/toon_boilerstatus.py", line 181, in update
    self._state = float(boilerstatus["roomTempSetpoint"])
TypeError: float() argument must be a string or a number, not 'NoneType'`

**Comment by cyberjunky** [comment]
Do you still have this error with latest hass and component?

**Comment by RaJeronimo** [comment]
yes. but not that often. And when it's occuring all the other Toon components reports an errors to. Maybe a connection issue?

HASSIO 0.65.6


```
Log Details (ERROR)
Tue Mar 27 2018 04:09:28 GMT+0200 (Central Europe Daylight Time)

Update for sensor.toon_room_temp_setpoint fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 204, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/toon_boilerstatus.py", line 149, in update
    self.data.update()
  File "/usr/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 319, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/sensor/toon_boilerstatus.py", line 98, in update
    self.data = requests.get(BASE_URL.format(self._host, self._port, '/boilerstatus/boilervalues.txt'), timeout=5).json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

This is the dev log in HASSIO

Update for sensor.toon_boiler_pressure fails
04:09 custom_components/sensor/toon_boilerstatus.py (ERROR)
Update for sensor.toon_boiler_setpoint fails
04:09 custom_components/sensor/toon_boilerstatus.py (ERROR)
Update for sensor.toon_boiler_intemp fails
04:09 custom_components/sensor/toon_boilerstatus.py (ERROR)
Update for sensor.toon_room_temp fails
04:09 custom_components/sensor/toon_boilerstatus.py (ERROR)
Update for sensor.toon_boiler_outtemp fails
04:09 custom_components/sensor/toon_boilerstatus.py (ERROR)
Update for sensor.toon_room_temp_setpoint fails
04:09 custom_components/sensor/toon_boilerstatus.py (ERROR)
Update for sensor.toon_boiler_modulation fails
04:09 custom_components/sensor/toon_boilerstatus.py (ERROR)
Update for climate.toon_thermostat fails
04:07 custom_components/climate/toon.py (ERROR)
Update for sensor.toon_power_use fails
04:06 custom_components/sensor/toon_smartmeter.py (ERROR)
Update for sensor.toon_power_use_cnt fails
04:06 custom_components/sensor/toon_smartmeter.py (ERROR)
Update for sensor.toon_gas_used_cnt fails
04:06 custom_components/sensor/toon_smartmeter.py (ERROR)
Update for sensor.toon_gas_used_last_hour fails
04:06 custom_components/sensor/toon_smartmeter.py (ERROR)
Update for sensor.toon_power_use fails
04:06 custom_components/sensor/toon_smartmeter.py (ERROR)
Update for sensor.toon_gas_used_last_hour fails
04:06 custom_components/sensor/toon_smartmeter.py (ERROR)

**Comment by rickvnl** [comment]
Any solution for this @cyberjunky? 
I have the same errors in 0.86.4.

**Comment by cyberjunky** [comment]
Is this still happening with latest code and 0.92 ?

**Comment by cyberjunky** [comment]
No reply
